# Generated by Django 4.2.30 on 2026-05-16 10:04

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRunLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_type', models.CharField(choices=[('sql', 'SQL Server'), ('oracle', 'Oracle')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], db_index=True, max_length=16)),
                ('session_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('systems', models.CharField(blank=True, help_text='SQL system labels or Oracle hostname', max_length=512)),
                ('source_filenames', models.TextField(blank=True, help_text='Comma-separated uploaded file names')),
                ('file_count', models.PositiveSmallIntegerField(default=0)),
                ('input_rows', models.PositiveIntegerField(blank=True, null=True)),
                ('exception_records', models.PositiveIntegerField(blank=True, null=True)),
                ('findings_count', models.PositiveIntegerField(blank=True, null=True)),
                ('exceptions_register_count', models.PositiveIntegerField(blank=True, null=True)),
                ('iapply_filter_applied', models.BooleanField(default=False)),
                ('date_format', models.CharField(blank=True, max_length=8)),
                ('error_message', models.TextField(blank=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'verbose_name': 'Review run',
                'verbose_name_plural': 'Review runs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at', 'review_type'], name='audit_revie_started_5ec7ad_idx')],
            },
        ),
    ]
